### ISSUE TITLE
Object of type PosixPath is not JSON serializable

### ISSUE THREAD

**Issue by ErickQ06** [Jesrat/django-process#4]
Error on python manage.py run_jobs execution
[ErrorLog.txt](https://github.com/Jesrat/django-process/files/9629838/ErrorLog.txt)

**Comment by Jesrat** [comment]
The error was due to Django's implementation of pathlib for specify settings.BASE_DIR, so when Django-process was trying to json dump the BASE_DIR the error is raised, cause "PosixPath is not JSON serializable", fixed on commit [9a49884](https://github.com/Jesrat/django-process/commit/9a49884f17b97f96a24cf050e1d4bc624e69b912), please use new Django-process version 4.7.9.
